### ISSUE TITLE
Water drops do not function as behavior intends

### ISSUE THREAD

**Issue by chrfoyer** [ninawrona/The-Secret-Garden---Template#3]
The assignment asks for the water drops to continually drop from the can. They should form again as soon as the drop leaves the bottom of the window

**Comment by KamilFischbach** [comment]
ROBERT WE BELIEVE IN DIG!

**Comment by KamilFischbach** [comment]
YOU GOT THUSI!

**Comment by KamilFischbach** [comment]
Mud and mud everywhere

**Comment by chrfoyer** [comment]
The drops should slightly vary where they load on the can

**Comment by robert-barta** [comment]
They doooohohohoo
